### ISSUE TITLE
IE11 With Angular 5 and EsriLoader and Version 3.x not working

### ISSUE THREAD

**Issue by joshbsommers** [Esri/esri-loader#82] opened 2018-01-24 23:34 UTC
We are currently using Angular 5 alongside JavaScript v3.x, with the esri-loader. 

We are using this string to configure the URL for 3.x: 
this._esriOptions = {
      url: 'https://js.arcgis.com/3.23/'
    };

The problem we are facing is we are not able to pan on the map in IE11. It pans just fine  in Chrome.  We are able to move through setting the center of the map, but this is not an elegant solution. We are able to zoom in/out and draw on the map. 

We also set it up using version 4.x in both chrome and IE11 and it works fine.

Any help would be much appreciated.

**Comment by andygup** [comment] 2018-01-24 23:40
@joshbsommers I don't have IE11 to test with. Were there any errors? Can you pan a non-Angular ArcGIS JS API 3.x app in IE11?

**Comment by jwasilgeo** [comment] 2018-01-24 23:41
@joshbsommers can you also recreate this situation in a jsfiddle or jsbin please?

**Comment by joshbsommers** [comment] 2018-01-24 23:46
There are no errors being thrown in the console as I attempt to move around. I can move around on any of the samples on the ESRI website, and have developed other apps using IE11 and JS API 3.x, this is my first one using Angular. This sample works fine: https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=toolbar_draw

@jwasilgeo I will work to create a jsfiddle or jsbin.

**Comment by joshbsommers** [comment] 2018-01-25 14:57
I was not able to get Angular working with JSFiddle or jsbin, but here is a sample component that demonstrates the issue: 

`import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { loadModules } from 'esri-loader';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'app';

  public map: any;
  public esriConfig: any;

  @ViewChild('map') private mapViewEl: ElementRef;

  public ngOnInit() {
    this.esriConfig = {
      url: 'https://js.arcgis.com/3.23/'
    };

    loadModules(["esri/map", "dojo/domReady!"], this.esriConfig).then(([Map]) => {
      this.map = new Map(this.mapViewEl.nativeElement, {
        basemap: "streets",
        center: [-15.469, 36.428],
        zoom: 3
      });
    });

  }

}
`

Here is my list of polyfills as well: 
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';
 import 'classlist.js';  // Run `npm install --save classlist.js`.

 import 'core-js/es6/reflect';
import 'core-js/es7/reflect';



 import 'web-animations-js';  // Run `npm install --save web-animations-js`.
import 'zone.js/dist/zone';  // Included with Angular CLI.

Please let me know if there is anything else I can provide. 

Thanks!

**Comment by andygup** [comment] 2018-01-25 15:55
@joshbsommers can you try an older version of the JS API just make sure it's not something that changed? 

@jwasilgeo lemme know if you need help digging in. It's not a good sign that it's failing silently. Makes me wonder if one of the polyfills is stepping on something.

**Comment by joshbsommers** [comment] 2018-01-25 16:05
@andygup I have tried all the versions back to 3.18 and it is the same behavior where it is not moving.

**Comment by jwasilgeo** [comment] 2018-01-25 16:11
Yeah before I try to fire this up myself I was wondering too if there is a mystery DOM element sitting on top of the map div that is blocking user input interactions.  Can you send a screenshot of your DOM structure, with some of the nested elements expanded, after the map is constructed and loaded?  Please just include 2 or 3 parent/child nodes above and below the node you construct the map in.

**Comment by joshbsommers** [comment] 2018-01-25 16:21
![image](https://user-images.githubusercontent.com/11097855/35399240-a946c872-01a8-11e8-8929-0cfd6e093cd8.png)

**Comment by jwasilgeo** [comment] 2018-01-25 17:04
And nothing particularly fishy going on with these nodes? 

`<app-root...` 

`<div style="text-align: center;" _ngcontent...`

**Comment by joshbsommers** [comment] 2018-01-25 17:23
Not that I can notice. The app-root is used in all Angular projects so I don't think it would cause any issues. The other element exists above the map and does not extend below its div.

**Comment by tomwayson** [comment] 2018-01-30 15:39
I don't think this will help but, you should not use `"dojo/domReady!"` w/ esri-loader.

**Comment by tomwayson** [comment] 2018-01-30 15:44
Is this an Angular CLI app? If so what version, and are you [using `polyfills.ts`](https://angular.io/guide/browser-support#enabling-polyfills)?

If not, how/when are your polyfills being loaded?

**Comment by joshbsommers** [comment] 2018-01-30 15:53
I have removed that in other projects, I must have accidentally left that in, for this sample. It does not make a difference. 

Yes it is, I am using Angular Version 5 with CLI Version 1.6.0

I am using polyfills.ts.

**Comment by tomwayson** [comment] 2018-01-30 15:57
OK

The best thing to do is to create a new empty Angular CLI project, add esri-loader, generate a component, put the above code into it, and publish that to GitHub (since you can't recreate in bin/fiddle). If you do that, I will pull it and investigate w/ IE11.

**Comment by joshbsommers** [comment] 2018-01-30 19:51
Please see this repo for a copy of the code that is not working. https://github.com/joshbsommers/EsriLoaderIE11Issue/tree/master/ESRISample%20-%20Copy

**Comment by jwasilgeo** [comment] 2018-01-31 22:16
I've confirmed I can recreate this in my own standalone test application.  I'll continue trying to debug this.

**Comment by jwasilgeo** [comment] 2018-01-31 22:30
Fascinating...

IE11:

- mousewheel zooming: YES 
- mouse panning: NO

IE10 emulation in IE11:

- mousewheel zooming: YES
- mouse panning: YES

**Comment by andygup** [comment] 2018-02-02 18:33
@joshbsommers @jwasilgeo I was able to get a sample app up and running on a borrowed laptop using IE `11.962` and the sample from [`angular-cli-esri`](https://github.com/andygup/angular-cli-esri). 

Didn't have any issues panning. 

Note: I did **not** load the `classlist.js` and `web-animations-js` polyfills. I haven't had a chance yet to see if loading these two causes the issue, but I have a suspicion about it related to how we handle map layers.

```
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';


/**
 * Required to support Web Animations `@angular/platform-browser/animations`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

```

**Comment by joshbsommers** [comment] 2018-02-02 23:30
I have not seen the same success you had with my sample project that I set up. I will work to follow the instructions in the application you referenced next week and get back to you.

**Comment by tomwayson** [comment] 2018-02-03 01:01
@joshbsommers 

Thanks for providing the example repo. I've cloned it, `cd`'d into ./ESRISample - Copy and then tried to run `ng serve`, but I get this error:

```bash
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/Users/tom/code/EsriLoaderIE11Issue/ESRISample - Copy/node_modules/@angular/cli/tasks/serve.js:51:63)
    at check_port_1.checkPort.then.port (/Users/tom/code/EsriLoaderIE11Issue/ESRISample - Copy/node_modules/@angular/cli/commands/serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Here's the output of `ng -v`

```bash 
Angular CLI: 1.6.7
Node: 8.9.4
OS: darwin x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
```

**Comment by joshbsommers** [comment] 2018-02-06 14:31
@tomwayson It appears as if Git ignored my .angluar-cli.json file, when I uploaded the project. I have now uploaded to my repo, please give that a try now.

**Comment by joshbsommers** [comment] 2018-02-06 16:02
@andygup which Operating system was the laptop on? I am currently running it using Windows 10. I followed through the steps you had in that repo and the map was still not panning in IE11.

**Comment by andygup** [comment] 2018-02-06 16:10
Sorry, my bad, I forgot to post an update late last night that I forgot to add the `esriConfig` containing the 3.x url to the `esriLoader` constructor. I was able repro that panning does not work in IE11 using the 3.x API + Angular 5. Also, adding/removing in the polyfills mentioned above didn't seem to make a difference.

I wasn't able to determine anything conclusive. I'll take another stab at it today.

**Comment by tomwayson** [comment] 2018-02-07 19:57
This does seem like a bug, but my guess is that it is not related to esri-loader.

One way to verify that would be to [`ng eject`](https://github.com/angular/angular-cli/wiki/eject) and configure webpack according to the [exclude and require](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/#exclude-and-require) pattern and use `import` statements instead of esri-loader. I'm not sure that's worth the effort, but if you've exhausted all other options that might be something you can try.

**Comment by andygup** [comment] 2018-02-08 20:44
And, another thing we should check is if the `Map` mouse/click events are working.

**Comment by joshbsommers** [comment] 2018-02-08 21:40
So the way we have been able to get it to work, is to load Version 3 in an IFrame and use it that way. We ended up doing everything we could in Version 4 and just did the drawing/editing as the user needed in Version 3 in an IFrame. 

We found that drawing new shapes seemed to work as expected on the map, but editing shapes was not working. Hope that helps. We still have no idea what is causing this to happen.

**Comment by tomwayson** [comment] 2018-02-08 22:27
Thanks for reporting back. I'm glad you got something working, and sorry that we didn't have a better solution for you.

**Comment by adam3039** [comment] 2018-02-26 06:45
Does anyone have any suggestions other than loading the map in an IFrame? We're running into this problem and it's a really big show stopper for some of our features.

Same issue, map pans fine on Google & Firefox, broken on IE11. Interestingly enough, the map on click event works, but the double click does not. Running 3.23 and Angular 5. Moving our entire project up to version 4.x of the js api isn't really an option at the moment. I've also tried defining (dblClick) events on the map div, but they seem to be very unreliable.

**Comment by tomwayson** [comment] 2018-02-26 14:31
@adam3039 did you try [my suggestion](https://www.amcharts.com/kbase/handling-mouse-events-on-line-graph/)?

**Comment by adam3039** [comment] 2018-02-26 15:56
Hi Tom,

First off, I really appreciate the work you've put into this project. 

In the article and section you referenced, it says that nobody has figured out how to do this with the Angular CLI. As I'm using the CLI quite extensively, is that a non-starter for this pattern?

**Comment by tomwayson** [comment] 2018-02-26 16:25
It is theoretically possible to use that pattern [now that you can eject from the CLI](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/#comment-3163968615).

**Comment by huoyixin** [comment] 2018-03-15 07:05
Hi @joshbsommers @tomwayson 
This issue was because of the `MSPointerMove` event can not register in the IE11 with angular5 ENV.
You can use this code and have a try.
```
document.addEventListener('MSPointerMove',function(){console.log('MSPointerMove Event')})
```


I have find the real reason was beacuse of the `zone.js` used by Angular. After I upgrade the `zone.js` from 0.8.11 to next, this issues will come out.

**Temporary solution was use `zone.js` which version under `0.8.11`.**
Also I will try to find the more clear reason, welcom more discussion about this issue.

**Comment by andygup** [comment] 2018-05-30 15:09
Looks like there's a workaround ☝️. I'm going to close this out for now.

**Closed by andygup** 2018-05-30 15:09 UTC
Labels: question

**Comment by n8all3n** [comment] 2018-08-21 20:59
So, is the only solution to this downgrading to zone.js version 0.8.12?

**Comment by arrow-dev** [comment] 2018-08-21 22:40
I'm also facing this problem, this issue is open in the zone.js repo https://github.com/angular/zone.js/issues/1080#issuecomment-385576711 one one the collaborators has provided a patch to add to polyfills.ts but for me this broke other parts of our angular app so I've had to resort to reverting to 0.8.12 for now.

**Comment by andygup** [comment] 2018-08-21 23:03
The current known workarounds still seem to be downgrade zone.js, upgrade to the ArcGIS JS API 4.x or use the patch mentioned by @arrow-dev ☝️. 

...if someone has ideas please post'em. I don't have easy access to IE11 for testing.
