### ISSUE TITLE
about esriLoader.dojoRequire() in vue

### ISSUE THREAD

**Issue by GwYL** [Esri/esri-loader#52] opened 2017-11-14 03:14 UTC
I always have this kind of problem:
When I use "esri/tasks/IdentifyTask", "esri/tasks/IdentifyParameters" or "esri/tasks/FindTask","esri/tasks/FindParameters" or
"esri/tasks/QueryTask","esri/tasks/Query".

Browsers always make the same mistake:
IdentifyTask.js:4 Uncaught (in promise) TypeError: Cannot read property 'path' of undefined.

But when I note this line of code: var params = new IdentifyParameters() , it's get right.
I don't konw how to solve it.

code:
          map.on("load", mapReady);

          var identifyTask = new IdentifyTask(parcelsURL)
          var identifyParams = new IdentifyParameters()
          function mapReady () {
            console.log(11111111)
            ...........
          }
And when I input this code to the function mapReady, it also have some problem: 
the basemap of the map can't be loaded in the first time, and this code can't be implemented.

code: 
          map.on("load", mapReady);

          function mapReady () {
            console.log(11111111)
            var identifyTask = new IdentifyTask(parcelsURL)
            var identifyParams = new IdentifyParameters()
            ...................
          }

**Comment by tomwayson** [comment] 2017-11-17 14:44
I suggest you try getting the map/identify code working entirely outside of Vue and esri-loader in https://jsbin.com/

Then if you're having problems getting the same to work in your Vue app after using esri-loader to load the modules, I can help.

**Comment by GwYL** [comment] 2017-11-21 02:28
The esri-loader entirely outside of Vue is all right, but I have getting the problems in Vue. And even the code is the same, some pages can , some pages can not in .vue.

**Comment by tomwayson** [comment] 2017-11-21 05:30
Do you have a link to the code that works outside of Vue?

Can you provide more of the code that is not working? There's not enough code above for me to see where the problem is. I'm not even able to tell what version of the ArcGIS API are you using.

**Comment by tomwayson** [comment] 2018-01-04 05:09
@GwYL were you able to solve your problem?

If so would you mind closing this issue?

If not, I've recently created [esri-vue-cli-example](https://github.com/tomwayson/esri-vue-cli-example) using the vue-cli's [webpack-simple template](https://github.com/vuejs-templates/webpack-simple) and it [demonstrates esri-loader code working in .vue files](https://github.com/tomwayson/esri-vue-cli-example/blob/master/src/HomeButton.vue). That may be of help to you.

**Comment by tomwayson** [comment] 2018-01-18 06:02
@GwYL I'm assuming you've resolved your issue and closing this for now. Feel free to re-open if needed.

**Closed by tomwayson** 2018-01-18 06:02 UTC
Labels: question
