### ISSUE TITLE
FeatureLayers not drawing

### ISSUE THREAD

**Issue by sasteigerwald** [Esri/esri-loader#251] opened 2020-11-05 21:20 UTC
I'm adding sublayers to dynamic map services as feature layers which has been working well and as expected until version 4.16. As of 4.17, they no longer work. I've opened a ticket with ESRI and they are claiming it works fine in 4.17 and that it could be the esri loader. While I doubt this, I am posting here to follow protocol. 

Some description of what happens:
- Most of the time, the featurelayer does not draw at all. I have verified that the featurelayer is present in the layers collection on the map and that there are no errors in network responses, no errors in the layer or layerview or map.
- Sometimes I can get the featurelayer to draw, but it will sometimes draw then disappear and other times it does persist on the map, but the extent is completely wrong.

I tried some things that ESRI suggested, including loading the layers using a sample app that is pure javascript, and the layer did load. This points to other areas, the esri-loader being one of them. I'd like to rule that out before escalating my ticket.

Environment: Angular 10, esri-loader 2.16

**Comment by sasteigerwald** [comment] 2020-11-12 00:04
Following up on this as I have not received any response. I also have more findings that points to this being an esri-loader specific issue.

I have tried a FeatureLayer an ESRI sample app (pure JavaScript) as well as an Angular 10 app with esri-loader. I found that it works 100% fine in the ESRI pure JS sample app. I then found that if I remove the definitionExpression in the Angular 10 app, it works. It appears that the esri-loader has broken FeatureLayers with definition expressions.

**Comment by andygup** [comment] 2020-11-12 15:40
@sasteigerwald it sounds like you have an open Esri tech support ticket, can you share the ticket number? If so, I'll circle back with tech support and get in contact with your support analyst.

This is certainly strange behavior because esri-loader uses simple script injection, it shouldn't be interfering with the ArcGIS JS API.

**Comment by sasteigerwald** [comment] 2020-11-12 15:47
@andygup, thanks for the response. The ticket is (was) a 02670741. They were not willing to trouble shoot the esri-loader since it is open source, so closed the ticket yesterday.

**Comment by andygup** [comment] 2020-11-12 15:50
Right, I mainly want to review their notes and get up to speed. Do you have a stackblitz sample or github repo that reproduces the behavior?

**Comment by sasteigerwald** [comment] 2020-11-12 18:49
@andygup I unfortunately do not have a good sample repo I can provide. The data I am testing is hosted internally and the failure is pretty clear with our data (which did work pre-4.17). If I swithc it out and use one of the ESRI sample datasets, it does seem to work fine. The main difference I see is the ESRI sample dataset is a FeatureServer, while our dataset is a sublayer (Feature Layer) of an image service.

It looks like the ES Modules could replace the esri-loader in the future? I may hold off upgrading until ES Modules is production ready, if need be.

**Comment by andygup** [comment] 2020-11-12 19:50
Can you try re-testing using esri-loader our `/next` build (4.18 pre-release)? 

`version: 'next'`

Also, for your internal hosting of the data, what version of ArcGIS Server is that?

**Comment by sasteigerwald** [comment] 2020-11-12 22:39
I did just try the next version, but get the same results. With a valid definitionExpression, the features do not display:
![image](https://user-images.githubusercontent.com/10838577/99004768-dd69f780-24fc-11eb-9983-e440bd1a0e0c.png)
Our app at 4.16 is using the definitionExpression being defined and that one works.

With the definitionExpression commented out, I get features:
![image](https://user-images.githubusercontent.com/10838577/99004843-f96d9900-24fc-11eb-8749-a9c78657eacc.png)

The ArcGIS Server version: Current Version: 10.71

**Comment by andygup** [comment] 2020-11-13 01:07
I'm having one of our MapImageLayer folks look at his. Some of this may have some to do with the processing being handled by the server, not the client. FeatureLayer is processed on the client.

**Comment by sasteigerwald** [comment] 2020-11-13 15:53
Thanks @andygup, much appreciated.

**Comment by andygup** [comment] 2020-11-18 16:49
@sasteigerwald just a quick update, we are still looking into this. Thanks for your patience.

**Comment by andygup** [comment] 2020-11-23 20:36
@sasteigerwald any chance you are using ngrx or something similar for state management? 

And, have you tried creating a super simple Angular app that only has MapImageLayer and Map?

**Comment by sasteigerwald** [comment] 2020-11-24 15:19
It looks like we have the ngrx package installed, but I see no references to it in code, so I do not think we are actively using it.

Yes, the screenshots I included a few comments up are from a completely new app. All I did with it is install angular, install the esri-loader and added a map, mapview and added the layer (as a featurelayer, not a mapimagelayer). Here's the code:

`import { Component } from '@angular/core';
import { loadModules } from 'esri-loader';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  constructor() { this.loadMap(); }

  loadMap() {
    const options = {
      version: 'next',
      css: true
    };
    // this will lazy load the ArcGIS API
    // and then use Dojo's loader to require the classes
    loadModules(['esri/views/MapView', 'esri/WebMap', 'esri/layers/FeatureLayer'], options)
    .then(([MapView, WebMap, FeatureLayer]) => {
      const featureLayer = new FeatureLayer({
        url:
          'http://ms-c1-na.internal.ems-energy-prod.ihsmarkitgis.com/arcgis/rest/services/ep/well/MapServer/1',
        definitionExpression: 'UWI IN (\'05123059060000\',\'05123059160000\',\'05123059200000\',\'05123059230000\')'
      });
      // then we load a web map from an id
      const webmap = new WebMap({
        basemap: 'hybrid',
        zoom: 13,
        center: [-98.5422, 39.2241],
        layers: [featureLayer]
      });
      // and we show that map in a container w/ id #viewDiv
      const view = new MapView({
        map: webmap,
        container: 'viewDiv',
      });
    })
    .catch(err => {
      // handle any errors
      console.error(err);
    });
  }
}
`

**Comment by andygup** [comment] 2020-11-25 00:37
@sasteigerwald I haven't been able to reproduce your issue. I think there are two options for moving forward. Option A: work with Tech Support to get access to your map service by doing a live screen share session, or Option B: have you create a publicly available service that recreates the issue.

The following component code is one of the test apps that I used to try and reproduce the issue. It works with esri-loader, @arcgis/core (ES modules) and the CDN:
* Angular 11
* `esri-loader 2.16`
* @arcgis/core version `4.18.0-next.20201119`
* CDN versions 4.17 and 4.18 (via next)

>> _The main difference I see is the ESRI sample dataset is a FeatureServer, while our dataset is a sublayer (Feature Layer) of an image service._

The FeatureLayer in this test is a sublayer of MapImageLayer. This matches what you described above. The sample server does occasionally throw CORS errors, but that's the only issue that I'm seeing.

```javascript
import {
  Component,
  OnInit,
  ViewChild,
  ElementRef,
  OnDestroy,
  NgZone
} from '@angular/core';

import { loadModules } from 'esri-loader';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit, OnDestroy {
  private view: any = null;

  // The <div> where we will place the map
  @ViewChild('mapViewNode', { static: true }) private mapViewEl: ElementRef;

  constructor(private zone: NgZone) { }

  initializeMap(): void {
    const container = this.mapViewEl.nativeElement;

    const options = {
      version: 'next',
      css: true
    };

    loadModules(['esri/views/MapView', 'esri/Map', 'esri/layers/FeatureLayer'], options)
      .then(([MapView, Map, FeatureLayer]) => {
        const featureLayer = new FeatureLayer({
          url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/0',
          definitionExpression: 'pop2000 > 100000'
        });

        const map = new Map({
          basemap: 'dark-gray-vector',
          layers: [featureLayer]
        });

        const view = new MapView({
          map: map,
          container: container,
          zoom: 4,
          center: [-103, 39.2241]
        });
      })
      .catch(err => {
        console.error(err);
      });
  }

  ngOnInit(): any {
    this.zone.runOutsideAngular(() => {
      this.initializeMap();
      console.log("Map ready");
    });
  }

  ngOnDestroy(): void {
    if (this.view) {
      this.view.destroy();
    }
  }
}
```
I also tested using the MapImageLayer Class directly as shown below and it worked, as. well:

```javascript
    const layer = new MapImageLayer({
      url:
        "https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer",
      sublayers: [
        {
          id: 3,
          visible: false
        },
        {
          id: 2,
          visible: true
        },
        {
          id: 1,
          visible: true
        },
        {
          id: 0,
          visible: true,
          definitionExpression: "pop2000 > 100000"
        }
      ]
    });   
```


![image](https://user-images.githubusercontent.com/510440/100165489-9cb49b80-2e77-11eb-8dde-65e8b8016e84.png)

**Comment by sasteigerwald** [comment] 2020-11-25 17:25
Thanks @andygup. I do have a premium support ticket that I will follow up on and see what we can do. Thanks again for looking into it.

**Comment by andygup** [comment] 2020-11-25 21:16
Sounds good @sasteigerwald. I forwarded my notes to our tech support liaison and your Esri Account rep. I'm going to go ahead and close this issue for now, and I'll get updates directly from support on the status of your case.

**Closed by andygup** 2020-11-25 21:16 UTC
