### ISSUE TITLE
vue中首次可以加载出地图来，但是一刷新页面就报错

### ISSUE THREAD

**Issue by harrylyh** [Esri/esri-loader#169] opened 2019-04-10 10:05 UTC
![image](https://user-images.githubusercontent.com/26681969/55870344-f4c35f00-5bba-11e9-99e5-15f18ac62d65.png)
![image](https://user-images.githubusercontent.com/26681969/55870448-2d633880-5bbb-11e9-9c95-d32757def6b4.png)

**Comment by tomwayson** [comment] 2019-04-11 19:48
can you reproduce this error somewhere like codesandbox?

**Comment by tomwayson** [comment] 2019-04-18 17:09
@harrylyh can you please see if this is fixed by bumping to [version 2.9.2](https://github.com/Esri/esri-loader/releases/tag/v2.9.2)?

**Comment by popovdenys** [comment] 2019-05-06 02:12
Hi @tomwayson,

Let me ask you a question. Every time I indicate the options like this 
```
const options = { url: 'https://js.arcgis.com/4.11/' }
```
or like
```
const options = { version: '4.11' }
```
or even when I leave the default options with
```
loadModules(['esri/map']).then(....
```
I get an error in the console: 
![Screenshot from 2019-05-05 22-07-11](https://user-images.githubusercontent.com/35589034/57203950-30ff9a80-6f82-11e9-9a52-817e88279c50.png)

and it's true - there is no such file as **https://js.arcgis.com/4.11/esri/map.js** but **https://js.arcgis.com/4.11/dojo/dojo.js**

But when I change the options to:
```
const options = { version: '3.28' }
loadModules(['esri/map'], options)
```

everything works fine

What could it be?

Cheers,
D.

**Comment by tomwayson** [comment] 2019-05-06 14:40
closing due to inactivity

**Closed by tomwayson** 2019-05-06 14:40 UTC
Labels: needs-repro
